name: Maven release action

inputs:
  java-version:
    required: true
  maven-args:
    default: clean deploy -Prelease -Dmaven.javadoc.skip=true -Dmaven.test.skip=true


runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with: 
        distribution: temurin
        java-version: ${{ inputs.java-version }}
        cache: maven

    - name: Setup settings 
      run: | 
        mkdir -p ~/.m2
        printf "%s" "${MAVEN_SETTINGS_XML}" \
          | sed "s|\${SONATYPE_USERNAME}|$SONATYPE_USERNAME|g" \
          | sed "s|\${SONATYPE_PASSWORD}|$SONATYPE_PASSWORD|g" \
          | sed "s|\${GPG_PASSPHRASE}|$GPG_PASSPHRASE|g" \
          > ~/.m2/settings.xml
      shell: bash

    - name: Configure GPG, no prompt take phrase as env
      run: |
        mkdir -p ~/.gnupg
        chmod 700 ~/.gnupg
        echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
      shell: bash

    - name: Import GPG key
      run: |
        echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --pinentry-mode loopback --import
      shell: bash

    - name: Run the mvn 
      run: mvn ${{ inputs.maven-args }} -B -Dgpg.passphrase="${GPG_PASSPHRASE}"
      shell: bash

