name: RELEASE

on: 
  workflow_call:
    inputs: 
      java-version: 
        type: string
        required: true
      maven-args: 
        type: string 
        default: "clean deploy -Prelease -DskipTests"
      os: 
        type: string
        default: "ubuntu-latest"
    secrets:
      GPG_PRIVATE_KEY: 
        required: true
      GPG_PASSPHRASE:
        required: true
      MAVEN_SETTINGS_XML: 
        required: true
      SONATYPE_USERNAME:
        required: true
      SONATYPE_PASSWORD: 
        required: true

jobs:
  release: 
    runs-on: ${{ inputs.os }}

    permissions:
      contents: write 
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Java for Release Job 
        uses: haidarim/ci-templates/.github/actions/nexus-publish/maven-release@v1.1.10
        with: 
          java-version: ${{ inputs.java-version }}
          maven-args: ${{ inputs.maven-args }}

        env: 
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_SETTINGS_XML: ${{ secrets.MAVEN_SETTINGS_XML }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Extract version
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag "v${{ steps.version.outputs.VERSION }}"
          git push origin "v${{ steps.version.outputs.VERSION }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: Release v${{ steps.version.outputs.VERSION }}
          generate_release_notes: true
