name: JAVA_DOC

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: true
      maven-args:
        type: string
        default: "clean verify -Dmaven.test.skip=true"
      os:
        type: string
        default: "ubuntu-latest"
jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Java tests
        uses: haidarim/ci-templates/.github/actions/setup-java/maven-build@v1.1.8
        with:
          java-version: ${{ inputs.java-version }}
          maven-args: ${{ inputs.maven-args }}

